; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.3 on Wed Sep 29 2021 19:26:52 GMT+0100 (British Summer Time)

