; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool on Tue Mar 13 2018 19:09:09 GMT+0000 (GMT Standard Time)
; Wait for set temperatures to be reached
M116 P1