; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.3 on Wed Sep 29 2021 19:26:52 GMT+0100 (British Summer Time)
; Wait for set temperatures to be reached
M116 P0

